### ISSUE TITLE
Error with Efficient Loader: 'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by luisinostrozaf** [fofr/cog-face-to-many#11]
i'm having this error: 

![imagen](https://github.com/fofr/cog-face-to-many/assets/50220590/112954a8-00aa-488a-817a-5431e5f81c66)

anyone know how to solve it?

**Comment by highwaywarrior0** [comment]
same here

**Comment by punchmello** [comment]
same issue

**Comment by Beriholic** [comment]
same issue

**Comment by Beriholic** [comment]
same issue

**Comment by luisinostrozaf** [comment]
well i solved it, but idk if its the same issue with you guys, i used this post: https://www.reddit.com/r/StableDiffusion/comments/18mebqk/nonetype_object_has_no_attribute_lower/ , basically checked every model that i was giving to the workflow, i'm gonna paste a screenshot of my workflow that is working, hopefully it works for you.
![face-to-many](https://github.com/fofr/cog-face-to-many/assets/50220590/a0c43407-7807-459f-8a57-685d86329302)
