### ISSUE TITLE
PS2

### ISSUE THREAD

**Issue by Sj013** [fofr/cog-face-to-many#14]

**Comment by Onizuka667** [comment]
![Uploading 66B91367-A273-470C-B543-23CB48B2DD8B.jpeg…]()

**Comment by Onizuka667** [comment]
![32C0C16D-6227-4A00-80E3-D1BDEF748F68](https://github.com/fofr/cog-face-to-many/assets/164258762/4bd7cc79-c4e8-466b-ba58-5317b45304d3)
![66B91367-A273-470C-B543-23CB48B2DD8B](https://github.com/fofr/cog-face-to-many/assets/164258762/75d8280c-f7eb-4f32-a11c-5b13a3d01e8f)

**Comment by boggdab** [comment]
![IMG_8107](https://github.com/fofr/cog-face-to-many/assets/164287701/110893b2-2d8b-4ac9-8266-705e31b6bcd2)

**Comment by YahavrjxjLrguwgz** [comment]
![Uploading IMG_9500.jpeg…]()
