### ISSUE TITLE
Face-to-many AI doesn't work

### ISSUE THREAD

**Issue by Ivanko2004** [fofr/cog-face-to-many#25]
Face-to-many AI doesn't work

**Comment by Ivanko2004** [comment]
![chrome_JsDurXaOmb](https://github.com/fofr/cog-face-to-many/assets/105988730/7180e8fe-4cb4-417e-973e-ae4ff8d3e4c9)

**Comment by e728974469** [comment]
yep, same question

**Comment by fofr** [comment]
This has now been resolved.

**Comment by e728974469** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
