### ISSUE TITLE
wrong file extension resolution [replicate]

### ISSUE THREAD

**Issue by esskayesss** [fofr/cog-face-to-many#32]
(just fyi, i'm coming from replicate) 
I used a file `Photo on 15-11-23 at 22.58 #2.jpeg` and the resolved extension was wrong.
```
Traceback (most recent call last):
File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/cog/server/worker.py", line 217, in _predict
result = predict(**payload)
File "/src/predict.py", line 223, in predict
filename = self.handle_input_file(image)
File "/src/predict.py", line 87, in handle_input_file
raise ValueError(f"Unsupported file type: {file_extension}")
ValueError: Unsupported file type: .58
```

Clearly, it's considering the `.58` in the `22.58` to be the file extension, which, of course isn't a valid file type.

**Comment by fofr** [comment]
I took a look into this and it seems to be a bug with the Replicate website – it strips anything after the `#` character, leaving a filename `Photo on 15-11-23 at 22.58 `, which makes the extension look like `.58`.

I've let the team know about this.
