### ISSUE TITLE
Why loading fails

### ISSUE THREAD

**Issue by lijunlin0** [fofr/cog-face-to-many#41]
![image](https://github.com/fofr/cog-face-to-many/assets/117365903/4421fe27-cc8f-4e25-bed9-43f03aa06e26)

**Comment by Blucknote** [comment]
You should download some custom nodes for that.

First of all you don't have manager. Install [manager](https://github.com/ltdrdata/ComfyUI-Manager) and then click `install custom missing nodes`. 

After you install nodes restart comfy and reload page and you should be fine

**Comment by fofr** [comment]
I've updated the README with further instructions thanks to #20
