### ISSUE TITLE
instantid-controlnet & instant-ip-adapter

### ISSUE THREAD

**Issue by P1nk-L0rD** [fofr/cog-face-to-many#5]
Where to download **instantid-controlnet.safetensors** & **instant-ip-adapter.bin**? I found only diffusion_pytorch_model.safetensors and ip-adapter.bin and the results are not that good.
Also i didn't get how to change style on local version, does it depends on prompt only?

**Comment by luisinostrozaf** [comment]
same issue here, i just downloaded the same files and changed the names to fill the ones in the json. Fixed the error but the promps doesnt work, did you solved it?

**Comment by aj47** [comment]
+1

**Comment by ajajaajaja** [comment]
> same issue here, i just downloaded the same files and changed the names to fill the ones in the json. Fixed the error but the promps doesnt work, did you solved it?

where did you get those files?

**Comment by luisinostrozaf** [comment]
i googled it, as pink lord said the names are diffusion_pytorch_model.safetensors and ip-adapter.bin, i dont remember the exact page tho

**Comment by aj47** [comment]
Yeah I also ended up getting them from huggingface and comfy manager. Will be making a tutorial on stream today on YouTube @techfren

**Comment by aj47** [comment]
https://github.com/aj47/techfren-vids/blob/main/comfyui/README.md

**Comment by MorozEslisho** [comment]
> https://github.com/aj47/techfren-vids/blob/main/comfyui/README.md

copy every move... but.. 😢 

![2](https://github.com/fofr/cog-face-to-many/assets/122890278/caf234b5-420b-4a77-b442-07ec1e66106b)

**Comment by 0Chencc** [comment]
> > https://github.com/aj47/techfren-vids/blob/main/comfyui/README.md
> 
> copy every move... but.. 😢
> 
> ![2](https://private-user-images.githubusercontent.com/122890278/316253425-caf234b5-420b-4a77-b442-07ec1e66106b.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzODk1NzUsIm5iZiI6MTcxMTM4OTI3NSwicGF0aCI6Ii8xMjI4OTAyNzgvMzE2MjUzNDI1LWNhZjIzNGI1LTQyMGItNGE3Ny1iNDQyLTA3ZWMxZTY2MTA2Yi5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNVQxNzU0MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMzZiMWViYjA5NzQ3NTIzN2ExZjM1ZWM5OWYzMDUwNjFjYTY2YWI2NmY3MTUxNmRmNGYwY2Q4M2ZkZGE3OGY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fqFf9TYqZL01O24ubffNEW20oCRI9brJ-_UlCskxDzE)

you can fix it when u reinstall Efficient Loader:[https://github.com/jags111/efficiency-nodes-comfyui](https://github.com/jags111/efficiency-nodes-comfyui)
